name: Type Check with Pyright

on: [push]
jobs:
  type-check:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.11"]
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install the package locally
          run:
            pip install -r requirements.txt
        - name: Pyright
          uses: jakebailey/pyright-action@v2
          with:
            version: 1.1.373
            project: "."

